### ISSUE TITLE
autohome.py运行没效果啊

### ISSUE THREAD

**Issue by firebear** [duanyifei/antispider#1]
span没有被替换：

`&nbsp;&nbsp;&nbsp;&nbsp;自去年12月12日提车之后<span class='hs_kw0_mainmx'></span>基本<span class='hs_kw1_mainmx'></span>就没驾驶博越去<span class='hs_kw2_mainmx'></span>点<span class='hs_kw3_mainass='hs_kw4_mainmx'></span>方<span class='hs_kw5_mainmx'></span>这次<span class='hs_kw6_mainmx'></span>朋友商量之后<span class='hs_kw0_mainmx'></span>决定自驾去天津<span class='hs_kw0_mainmx'></s='hs_kw7_mainmx'></span>可以带<span class='hs_kw8_mainmx'></span><span class='hs_kw9_mainmx'></span>越越<span class='hs_kw0_mainmx'></span>去欣赏<span class='hs_kw10_mainmx'></span><span class='hainmx'></span>他乡<span class='hs_kw3_mainmx'></span>风光<span class='hs_kw5_mainmx'></span>由于<span class='hs_kw12_mainmx'></span>第<span class='hs_kw10_mainmx'></span>次去天津<span class='hs_k</span>所以道路<span class='hs_kw1_mainmx'></span><span class='hs_kw13_mainmx'></span>太熟悉<span class='hs_kw0_mainmx'></span>还<span class='hs_kw7_mainmx'></span>博越为我提供<span class='hs_kw1x'></span>精准<span class='hs_kw3_mainmx'></span>导航系统<span class='hs_kw0_mainmx'></span>跟随<span class='hs_kw8_mainmx'></span>博野<span class='hs_kw3_mainmx'></span>脚步<span class='hs_kw0_mn>踏<span class='hs_kw1_mainmx'></span>前往天津<span class='hs_kw3_mainmx'></span>征程<span class='hs_kw5_mainmx'></span><br />&nbsp;&nbsp;&nbsp;全程<span class='hs_kw15_mainmx'></span>速<span cl0_mainmx'></span>由保定北<span class='hs_kw1_mainmx'></span>京港澳<span class='hs_kw15_mainmx'></span>速北京方向<span class='hs_kw0_mainmx'></span>再转入荣乌<span class='hs_kw15_mainmx'></span>速'hs_kw5_mainmx'></span><span class='hs_kw10_mainmx'></span>路由朋友担当摄影<span class='hs_kw0_mainmx'></span>拍<span class='hs_kw3_mainmx'></span>照片都<span class='hs_kw12_mainmx'></span>路<spaw1_mainmx'></span><span class='hs_kw3_mainmx'></span>风景<span class='hs_kw5_mainmx'></span><span class='hs_kw15_mainmx'></span>速途中<span class='hs_kw10_mainmx'></span>路驾驶博越<span class='hsx'></span>给我<span class='hs_kw3_mainmx'></span>感觉非常稳重<span class='hs_kw0_mainmx'></span>方向指向精准<span class='hs_kw5_mainmx'></span><span class='hs_kw13_mainmx'></span><span class='hs_/span><span class='hs_kw13_mainmx'></span>说<span class='hs_kw0_mainmx'></span>吉利真<span class='hs_kw3_mainmx'></span><span class='hs_kw12_mainmx'></span>在用心造车<span class='hs_kw0_mainmx'><越<span class='hs_kw0_mainmx'></span>已经成为同级别车型中<span class='hs_kw3_mainmx'></span>标杆产品<span class='hs_kw5_mainmx'></span><br />&nbsp;&nbsp;<span class='hs_kw11_mainmx'></span>面<spamainmx'></span>就为<span class='hs_kw17_mainmx'></span>家奉<span class='hs_kw1_mainmx'></span>精美<span class='hs_kw17_mainmx'></span>图
`

**Comment by dytttf** [comment]
把你的测试代码发给我我看一下

**Comment by firebear** [comment]
我就是直接运行这个py程序的。难道还有哪儿没做么？

**Comment by firebear** [comment]
Traceback (most recent call last):
  File "autohome.py", line 313, in get_complete_text_autohome
    char_list = get_char(js.group(1))
  File "autohome.py", line 284, in get_char
    string = urllib.unquote(string_m.group(1)).decode("utf8")
AttributeError: 'NoneType' object has no attribute 'group'

**Comment by dytttf** [comment]
第277行是有问题，寻找var变量的正则可能会把js中的关键代码匹配上，导致这里关键代码全删了。。。，好神奇，我下午测试也没发现有这种现象，你一测就出来了

**Comment by firebear** [comment]
厉害，解决了！

**Comment by ieliwb** [comment]
Traceback (most recent call last):
  File "/home/www/default/autohome.py", line 334, in get_complete_text_autohome
    char_list = get_char(js)
  File "/home/www/default/autohome.py", line 304, in get_char
    index_list = index_m.group(1).split(";")
AttributeError: 'NoneType' object has no attribute 'group'
空间确实了点




你好，这个是什么问题呢，这篇文章测试的http://club.autohome.com.cn/bbs/thread-c-2561-64686945-1.html

**Comment by dytttf** [comment]
已修复
