### ISSUE TITLE
文字顺序问题

### ISSUE THREAD

**Issue by jianjianxin** [duanyifei/antispider#6]
请教一下：
这是我正则之后出来的JS一段。
(%E3%80%82%E4%B8%80%E4%B8%89%E4%B8%8A%E4%B8%8B%E4%B8%8D%E4%BA%86%E4%BA%8C%E4%BD%8E%E5%92%8C%E5%9C%B0%E5%A4%9A%E5%A4%A7%E5%A5%BD%E5%B0%91%E5%BE%88%E5%BE%97%E6%98%AF%E7%9A%84%E7%9D%80%E8%BF%91%E9%AB%98%EF%BC%81%EF%BC%8CNx_());=IK_((Nx_()1;11;18;23;13;17;3;0;6;8;22;9;5;19;20;15;12;7;10;4;2;21;16;14),hZ_(;))
解析出来的文字为（。一三上下不了二低和地多大好少很得是的着近高！，）所以想问一下1;11;18;23;13;17;3;0;6;8;22;9;5;19;20;15;12;7;10;4;2;21;16;14是表示文字的索引吗，是hs_kw(索引)_mainBf吗，

**Comment by dytttf** [comment]
文字			。一三上下不了二低和地多大好少很得是的着近高！，
中间索引		1;11;18;23;13;17;3;0;6;8;22;9;5;19;20;15;12;7;10;4;2;21;16;14
has_kw		0,1, 2, 3, 4, 5, 6

0 --> 1 --> 一 (文字[1])
1 --> 11 --> 多 (文字[11])

has_kw(i) = 文字[中间索引[i]]
